service: canopy-interview-backend

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'yarn'
    excludeFiles: src/**/*.test.[t|j]s
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, "local"}
  region: eu-west-1
  environment:
    STAGE: ${self:provider.stage}

functions:
  mediaSearch:
    handler: src/index.default
    events:
      - http:
          path: /
          method: get
          cors: true
